kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0032
  uid: a0558bed-5f35-4187-91e2-c40c84bf7891
  resourceVersion: '59587'
  creationTimestamp: '2022-10-28T13:21:07Z'
  labels:
    volume: pv0032
  finalizers:
    - kubernetes.io/pv-protection
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-09-09T16:16:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:phase': {}
      subresource: status
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-10-28T13:21:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:finalizers':
            .: {}
            'v:"kubernetes.io/pv-protection"': {}
          'f:labels':
            .: {}
            'f:volume': {}
        'f:spec':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:hostPath':
            .: {}
            'f:path': {}
            'f:type': {}
          'f:persistentVolumeReclaimPolicy': {}
          'f:volumeMode': {}
spec:
  capacity:
    storage: 100Gi
  hostPath:
    path: /mnt/pv-data/pv0032
    type: ''
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  volumeMode: Filesystem
status:
  phase: Available
