apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: on-demand-build-base-image-v2
spec:
  params:
    - description: Name of the ImageStream
      name: imagestream-name
      type: string
    - description: ImageStreamTag of the ImageStream(Optional)
      name: imagestream-tag
      type: string
  tasks:
    - name: checkout-base-images
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
      - name: url
        value: "git@gitlab.com:hcs-company/hcs-base-updater.git"
      - name: revision
        value: "main"
      - name: sslVerify
        value: "false"
      - name: deleteExisting
        value: "true"
      workspaces:
      - name: output
        workspace: base-images-git

    - name: check-imagestream
      params:
        - name: imagestream-name
          value: "$(params.imagestream-name)"
      taskRef:
        kind: Task
        name: check-imagestream
      workspaces:
      - name: base-images-git
        workspace: base-images-git
      runAfter:
      - checkout-base-images

    - name: get-imagestream-tags-v2
      params:
        - name: imagestream-name
          value: "$(params.imagestream-name)"
        - name: imagestream-tag
          value: "$(params.imagestream-tag)"
      taskRef:
        kind: Task
        name: get-imagestream-tags-v2
      workspaces:
        - name: base-images-git
          workspace: base-images-git
      runAfter:
        - check-imagestream

    - name: build-base-images
      params:
        - name: imagestream-name
          value: "$(params.imagestream-name)"
        - name: imagestream-tags
          value: "$(tasks.get-imagestream-tags-v2.results.imagestream-tags)"
      taskRef:
        kind: Task
        name: build-base-images
      workspaces:
      - name: base-images-git
        workspace: base-images-git
      runAfter:
      - get-imagestream-tags-v2

  workspaces:
  - name: base-images-git

